MYSQL_USER = 'nfc_payment'
MYSQL_PASSWORD = '******'
MYSQL_HOST = '127.0.0.1'

DATABASE_NAME = 'nfc_payment'

USERS_TABLE_NAME = 'users'
USER_NAME_COL = 'user_name'
CARD_ID_COL = 'card_id'
ADMIN_PRIVILEGE_COL = 'admin_privilege'
CREDIT_BALANCE_COL = 'credit_balance'
USER_ID_COL = 'user_id'

TRANSACTION_LOG_TABLE_NAME = 'transaction_log'
TRANSACTION_ID_COL = 'transaction_id'
TRANSACTION_AMOUNT_COL = 'transaction_amount'
TRANSACTION_DATETIME_COL = 'transaction_datetime'
TRANSACTION_TERMINAL_ID_COL = 'transaction_terminal_id'
TRANSACTION_INITIALIZEDBY_USER_ID_COL = 'transaction_initializedby_user_id'
TRANSACTION_USER_ID_COL = 'transaction_user_id'

TERMINALS_TABLE_NAME = 'terminals'
TERMINAL_ID_COL = 'terminal_id'
TERMINAL_HARDWAREIDENTIFIER_COL = 'TERMINAL_HARDWAREIDENTIFIER'
TERMINAL_NAME_COL = 'terminal_name'
TERMINAL_ENABLED_COL = 'terminal_enabled'
TERMINAL_AMOUNT_COL = 'terminal_amount'
TERMINAL_MESSAGE_COL = 'terminal_message'
